### PR TITLE
Issue #299 : Handle decimal values starting with ' . '

### PR DESCRIPTION
**Pull request by ng185115**
Issue https://github.com/cchanxzy/react-currency-input-field/issues/299

- This fix is specifically targeted to handle decimal input when ' . ' is entered. 
- Added neccessary tests.
- Tests are passing locally.

Built and tested.

### CODE REVIEW

**Comment by ng185115** [comment]
Hi @cchanxzy 

Can you please review this PR and if possible, could you consider merging this PR at your earliest convenience?

**Comment by cchanxzy** [comment]
Thanks for your PR @ng185115!

>In this PR I have fixed it only for decimal numbers , if you want this to be applicable for other decimal separators as well I can modify this condition to
>
> if (decimalSeparator && decimalSeparator !== '-' && value.startsWith(decimalSeparator)) { value = '0' + value; }
>
> I'm excluding this ' - ' decimal separator as we doesn't know if that first character is intended to be the separator or negative sign.

Yes I think that's a good suggestion, if you update the PR with your suggestion I'll be happy to merge it.

**Comment by ng185115** [comment]
Hi @cchanxzy 
Made changes to support all decimal separators , Can you please review and merge it as soon as possible?

**Comment by cchanxzy** [comment]
Merged. Thanks @ng185115 !

**Comment by ng185115** [comment]
Thanks @cchanxzy !! 
When can we expect this to be published ?

**Comment by cchanxzy** [comment]
Ah just realised that the commit message didn't follow the semantic release convention, so it didn't trigger a release. That's on me, I should have checked.

I've just made a commit to trigger the release, so this commit will be included.

**Comment by ng185115** [comment]
Thanks @cchanxzy !

**Pull request merged**
