### PR TITLE
Return number as a third argument on onChange event

### PR DESCRIPTION
**Pull request by elviss339**
On change is returning formatted number. 

DE locale user: 123.456,78 => parsing as float will return 123.467 because of the comma.
EN locale user: 123,456.78 => parsing as float will return 123 also because of the comma.

We need number representation of what user types.

### CODE REVIEW

**Comment by elviss339** [comment]
@cchanxzy can you please review this?

**Comment by cchanxzy** [comment]
Hi @elviss339, thanks for the PR. 

Your implementation only takes into account the group/decimal separator as `,` or `.` , whereas it could be ` ` (space) or `-` or something else because there's no restriction at the moment. Could you add some more test cases?

I really appreciate the contribution, and think it will be a good addition!

**Comment by elviss339** [comment]
@cchanxzy thanks I think I can manage to work with ` ` or `-` but the thing that worries me is that user can add custom decimal/group separators, how should we match that?

**Comment by elviss339** [comment]
@cchanxzy I've improved the `parseFloat` function. 

`groupSeparator` and `decimalSeparator` can be string or undefined now.

1. If `groupSeparator` is undefined means we get a whole number in that case we can parse as number and return.  
2. If `decimalSeparator` is undefined means we get number like this `12.50` or `12,50` in that case we'll replace the `groupSeparator` with a `.` and parse as float
3. We'll check whether we have decimal value, in case there's no decimal value, return int.
4. We are sure we got a number that is formatted at this step, therefore we're going to divide our work into two phases.

Phaase 1:
Remove group separators from the number with Regex. Number like this `5-033-121,5899` will become `5033121,5899`. Keep in mind that this Regex is dynamic, whatever group separator is passed it will remove it number can be `5x033x3,133` and it will be `50333.133` 

Phase 2:
Get a number `5033121,5899` and replace it's decimal separator with a `.`

**Comment by cchanxzy** [comment]
@elviss339 Thanks for the PR and amending, but I think your implementation is a bit more complicated than it needs to be, because most of it value "cleaning" is done at some point, and we don't need to do it again.

Hope you don't mind that I've made the changes myself here: https://github.com/cchanxzy/react-currency-input-field/pull/199

**Pull request closed without merging**
